[v1]
"bottom 0.10.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 16.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"du-dust 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"grex 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hx 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"tealdeer 1.7.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"watchexec-cli 2.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"zoxide 0.9.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
