[v1]
"bottom 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 13.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"du-dust 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"grex 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hx 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"tealdeer 1.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"watchexec-cli 1.25.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["watchexec"]
"zoxide 0.9.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
