code --install-extension IBM.output-colorizer
code --install-extension Zignd.html-css-class-completion
code --install-extension alexdima.copy-relative-path
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension formulahendry.auto-rename-tag
code --install-extension humao.rest-client
code --install-extension James-Yu.latex-workshop
code --install-extension joffreykern.markdown-toc
code --install-extension josa.markdown-table-formatter
code --install-extension mechatroner.rainbow-csv
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-python.python
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension rbbit.typescript-hero
code --install-extension robertohuertasm.vscode-icons
code --install-extension ryu1kn.partial-diff
code --install-extension shinnn.stylelint
code --install-extension sleistner.vscode-fileutils
code --install-extension victormejia.one-monokai-darker
code --install-extension vthiery.prettify-selected-json
