[v1]
"alacritty 0.14.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"bandwhich 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.10.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 16.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"diskonaut 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskonaut"]
"du-dust 1.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"eza 0.20.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"fd-find 10.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"gitweb 0.3.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitweb"]
"grex 1.4.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hx 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"hyperfine 1.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"macchina 6.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["macchina"]
"procs 0.14.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"rmesg 1.0.21 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmesg"]
"tealdeer 1.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"zoxide 0.9.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
