[v1]
"bandwhich 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bottom 0.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 6.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"diesel_cli 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"du-dust 0.5.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"git-delta 0.7.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"gitweb 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitweb"]
"grex 1.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"navi 2.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["navi"]
"procs 0.11.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"tealdeer 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
