[v1]
"alacritty 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["alacritty"]
"bandwhich 0.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.18.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bottom 0.6.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"cargo-update 8.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-install-update", "cargo-install-update-config"]
"diskonaut 0.11.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["diskonaut"]
"du-dust 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"exa 0.10.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["exa"]
"fd-find 8.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"fnm 1.28.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["fnm"]
"git-delta 0.11.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"gitweb 0.3.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["gitweb"]
"grex 1.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"hx 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"hyperfine 1.12.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"kiro-editor 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["kiro"]
"procs 0.11.13 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"rm-improved 0.13.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rip"]
"rmesg 1.0.18 (registry+https://github.com/rust-lang/crates.io-index)" = ["rmesg"]
"shut 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["shut"]
"tealdeer 1.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 12.1.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"zoxide 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["zoxide"]
